import "~/styles/globals.css";
import { Toaster } from "~/components/ui/toaster";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import NavBar from "~/components/NavBar";
import Providers from "~/providers";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Providers>
          <main className="flex min-h-screen flex-col bg-muted/40 lg:flex-row">
            <NavBar.Sheet />
            <NavBar.Content className="hidden lg:flex" />
            <div className="flex-1 bg-muted/40 p-4">{children}</div>
          </main>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
